import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  mainSidebar: [
    {
      type: 'doc',
      id: 'index',
      label: 'Home',
    },
    {
      type: 'doc',
      id: 'recovery/index',
      label: 'Agent Recovery Prompt',
    },
    {
      type: 'category',
      label: 'Executive Overview',
      link: {type: 'generated-index', slug: '/executive-overview'},
      items: [{type: 'autogenerated', dirName: 'executive-overview'}],
    },
    {
      type: 'category',
      label: 'Ecosystem Entities',
      link: {type: 'generated-index', slug: '/ecosystem-entities'},
      items: [{type: 'autogenerated', dirName: 'ecosystem-entities'}],
    },
    {
      type: 'category',
      label: 'Protocols',
      link: {type: 'generated-index', slug: '/protocols'},
      items: [{type: 'autogenerated', dirName: 'protocols'}],
    },
    {
      type: 'category',
      label: 'Audiences',
      link: {type: 'generated-index', slug: '/audiences'},
      items: [
        {
          type: 'category',
          label: '01 — Governments & Ministries',
          link: {type: 'generated-index', slug: '/audiences/01-governments'},
          items: [{type: 'autogenerated', dirName: 'audiences/01-governments'}],
        },
        {
          type: 'category',
          label: '02 — Defense / Security / Intelligence',
          link: {type: 'generated-index', slug: '/audiences/02-defense-security'},
          items: [{type: 'autogenerated', dirName: 'audiences/02-defense-security'}],
        },
        {
          type: 'category',
          label: '03 — National Critical Infrastructure',
          link: {type: 'generated-index', slug: '/audiences/03-critical-infrastructure'},
          items: [{type: 'autogenerated', dirName: 'audiences/03-critical-infrastructure'}],
        },
        {
          type: 'category',
          label: '04 — International Institutions',
          link: {type: 'generated-index', slug: '/audiences/04-international-institutions'},
          items: [{type: 'autogenerated', dirName: 'audiences/04-international-institutions'}],
        },
        {
          type: 'category',
          label: '05 — Dynasties & Royal Houses',
          link: {type: 'generated-index', slug: '/audiences/05-dynasties'},
          items: [{type: 'autogenerated', dirName: 'audiences/05-dynasties'}],
        },
        {
          type: 'category',
          label: '06 — Family Offices',
          link: {type: 'generated-index', slug: '/audiences/06-family-offices'},
          items: [{type: 'autogenerated', dirName: 'audiences/06-family-offices'}],
        },
        {
          type: 'category',
          label: '07 — Multinational Corporate Empires',
          link: {type: 'generated-index', slug: '/audiences/07-multinationals'},
          items: [{type: 'autogenerated', dirName: 'audiences/07-multinationals'}],
        },
        {
          type: 'category',
          label: '08 — Legacy Enterprises',
          link: {type: 'generated-index', slug: '/audiences/08-legacy-enterprises'},
          items: [{type: 'autogenerated', dirName: 'audiences/08-legacy-enterprises'}],
        },
        {
          type: 'category',
          label: '09 — Banks, Insurers, Financial Foundations',
          link: {type: 'generated-index', slug: '/audiences/09-banks-insurers'},
          items: [{type: 'autogenerated', dirName: 'audiences/09-banks-insurers'}],
        },
        {
          type: 'category',
          label: '10 — National Industry Bodies',
          link: {type: 'generated-index', slug: '/audiences/10-industry-bodies'},
          items: [{type: 'autogenerated', dirName: 'audiences/10-industry-bodies'}],
        },
        {
          type: 'category',
          label: '11 — Education / R&D / Think Tanks',
          link: {type: 'generated-index', slug: '/audiences/11-education-rd'},
          items: [{type: 'autogenerated', dirName: 'audiences/11-education-rd'}],
        },
        {
          type: 'category',
          label: '12 — Consulting Firms & System Integrators',
          link: {type: 'generated-index', slug: '/audiences/12-consulting-si'},
          items: [{type: 'autogenerated', dirName: 'audiences/12-consulting-si'}],
        },
        {
          type: 'category',
          label: '13 — Investors / VCs / Syndicates',
          link: {type: 'generated-index', slug: '/audiences/13-investors-vc'},
          items: [{type: 'autogenerated', dirName: 'audiences/13-investors-vc'}],
        },
        {
          type: 'category',
          label: '14 — High-Power Founders & Operators',
          link: {type: 'generated-index', slug: '/audiences/14-founders-operators'},
          items: [{type: 'autogenerated', dirName: 'audiences/14-founders-operators'}],
        },
        {
          type: 'category',
          label: '15 — High-Risk Individuals',
          link: {type: 'generated-index', slug: '/audiences/15-high-risk-individuals'},
          items: [{type: 'autogenerated', dirName: 'audiences/15-high-risk-individuals'}],
        },
      ],
    },
    {
      type: 'category',
      label: 'Platform',
      link: {type: 'generated-index', slug: '/platform'},
      items: [
        {
          type: 'category',
          label: 'Core Systems (42)',
          link: {type: 'generated-index', slug: '/platform/core-systems'},
          items: [{type: 'autogenerated', dirName: 'platform/core-systems'}],
        },
        {
          type: 'category',
          label: 'Agent Library (200+)',
          link: {type: 'generated-index', slug: '/platform/agents'},
          items: [{type: 'autogenerated', dirName: 'platform/agents'}],
        },
        {
          type: 'category',
          label: 'Primitive Roles (12)',
          link: {type: 'generated-index', slug: '/platform/primitives'},
          items: [{type: 'autogenerated', dirName: 'platform/primitives'}],
        },
        {
          type: 'category',
          label: 'Infrastructure Layers (19)',
          link: {type: 'generated-index', slug: '/platform/infrastructure-layers'},
          items: [{type: 'autogenerated', dirName: 'platform/infrastructure-layers'}],
        },
        {
          type: 'category',
          label: 'OpenClaw Runtime',
          link: {type: 'generated-index', slug: '/platform/openclaw'},
          items: [{type: 'autogenerated', dirName: 'platform/openclaw'}],
        },
        {
          type: 'category',
          label: 'Doc-as-Code',
          link: {type: 'generated-index', slug: '/platform/doc-as-code'},
          items: [{type: 'autogenerated', dirName: 'platform/doc-as-code'}],
        },
        {
          type: 'category',
          label: 'Blockchain & IoT',
          link: {type: 'generated-index', slug: '/platform/blockchain-iot'},
          items: [{type: 'autogenerated', dirName: 'platform/blockchain-iot'}],
        },
        {
          type: 'category',
          label: 'Consumer Apps',
          link: {type: 'generated-index', slug: '/platform/consumer-apps'},
          items: [{type: 'autogenerated', dirName: 'platform/consumer-apps'}],
        },
      ],
    },
    {
      type: 'category',
      label: 'Economic Model',
      link: {type: 'generated-index', slug: '/economic-model'},
      items: [
        {type: 'autogenerated', dirName: 'economic-model'},
      ],
    },
    {
      type: 'category',
      label: 'Market Intelligence',
      link: {type: 'generated-index', slug: '/market-intelligence'},
      items: [
        {
          type: 'category',
          label: 'Chokepoints (100)',
          link: {type: 'generated-index', slug: '/market-intelligence/chokepoints'},
          items: [{type: 'autogenerated', dirName: 'market-intelligence/chokepoints'}],
        },
        {
          type: 'category',
          label: 'Market Wedges (6)',
          link: {type: 'generated-index', slug: '/market-intelligence/market-wedges'},
          items: [{type: 'autogenerated', dirName: 'market-intelligence/market-wedges'}],
        },
      ],
    },
    {
      type: 'category',
      label: 'Cross-Audience Analysis',
      link: {type: 'generated-index', slug: '/cross-audience'},
      items: [{type: 'autogenerated', dirName: 'cross-audience'}],
    },
    {
      type: 'category',
      label: 'Operations',
      link: {type: 'generated-index', slug: '/operations'},
      items: [
        {
          type: 'category',
          label: 'Frankmax Services (7)',
          link: {type: 'generated-index', slug: '/operations/frankmax-services'},
          items: [{type: 'autogenerated', dirName: 'operations/frankmax-services'}],
        },
        {
          type: 'category',
          label: 'LevelUpMax Bootcamp (10)',
          link: {type: 'generated-index', slug: '/operations/levelupmax'},
          items: [{type: 'autogenerated', dirName: 'operations/levelupmax'}],
        },
      ],
    },
    {
      type: 'category',
      label: 'Sovereign Intent Fabric',
      link: {type: 'generated-index', slug: '/sovereign-intent-fabric'},
      items: [
        {type: 'autogenerated', dirName: 'sovereign-intent-fabric'},
      ],
    },
    {
      type: 'category',
      label: 'Enhancement Layer (110)',
      link: {type: 'doc', id: 'enhancement-layer/index'},
      items: [{type: 'autogenerated', dirName: 'enhancement-layer'}],
    },
    {
      type: 'category',
      label: 'Organizational Formalization',
      link: {type: 'generated-index', slug: '/organizational-formalization'},
      items: [{type: 'autogenerated', dirName: 'organizational-formalization'}],
    },
    {
      type: 'category',
      label: 'Education & Workforce Intelligence',
      link: {type: 'generated-index', slug: '/education-workforce'},
      items: [{type: 'autogenerated', dirName: 'education-workforce'}],
    },
    {
      type: 'category',
      label: 'Sovereign Entropy Analysis',
      link: {type: 'doc', id: 'sovereign-entropy-analysis/index'},
      items: [{type: 'autogenerated', dirName: 'sovereign-entropy-analysis'}],
    },
    {
      type: 'category',
      label: 'Risk & Governance',
      link: {type: 'generated-index', slug: '/risk-governance'},
      items: [{type: 'autogenerated', dirName: 'risk-governance'}],
    },
  ],
};

export default sidebars;
